In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./02 - Biblioteca Pandas/08 - Pandas - Carregando Dados/datasets/base_vendas.csv')

In [6]:
df.head(3)

matricula_funcionario Nome Funcionario     Cargo codigo_loja    nome_loja  \
0              123456111       José Maria  Vendedor       CL001  Loja Matriz   
1              123456111       José Maria  Vendedor       CL001  Loja Matriz   
2              123456111       José Maria  Vendedor       CL001  Loja Matriz   

   codigo_produto descricao_produto         Categoria preco_custo  \
0           10013             Fogão  Eletrodomésticos       210,9   
1           10018           Colchão              Casa       109,9   
2           10014         Geladeira  Eletrodomésticos       699,9   

  valor_unitario  quantidade comissao          dt_venda        dt_entrega  
0          404,1           1      NaN  28/09/2020 16:19  05/10/2020 16:31  
1          249,9           1      NaN  07/03/2020 12:47  08/03/2020 12:47  
2         1346,9           1      NaN  21/04/2019 10:48  23/04/2019 15:55

In [7]:
df.tail(3)

matricula_funcionario Nome Funcionario     Cargo codigo_loja  nome_loja  \
2997              123457113      Victor Hugo  Vendedor       CL004  Filial ES   
2998              123457113      Victor Hugo  Vendedor       CL004  Filial ES   
2999              123457113      Victor Hugo  Vendedor       CL004  Filial ES   

      codigo_produto    descricao_produto         Categoria preco_custo  \
2997           10007            Batedeira           Cozinha        49,9   
2998           10010  Fritadeira elétrica           Cozinha       187,9   
2999           10004  Máquina Lavar Roupa  Eletrodomésticos        1099   

     valor_unitario  quantidade comissao          dt_venda        dt_entrega  
2997           95,9           3      NaN  08/08/2020 14:46  09/08/2020 14:07  
2998            340           3      NaN  19/12/2019 09:21  19/12/2019 10:51  
2999         1709,1           3     0,09  18/03/2019 15:40  23/03/2019 17:52

In [9]:
df.describe().T.round(1)

count         mean    std          min          25%  \
matricula_funcionario  3000.0  123456680.8  349.0  123456111.0  123456333.0   
codigo_produto         3000.0      10010.5    5.8      10001.0      10006.0   
quantidade             3000.0          2.5    1.1          1.0          1.0   

                               50%          75%          max  
matricula_funcionario  123456666.0  123456999.0  123457113.0  
codigo_produto             10011.0      10015.0      10020.0  
quantidade                     2.0          3.0          4.0

In [10]:
df.index

RangeIndex(start=0, stop=3000, step=1)

In [11]:
df.columns

Index(['matricula_funcionario', 'Nome Funcionario', 'Cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'Categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

In [12]:
df.nome_loja


0       Loja Matriz
1       Loja Matriz
2       Loja Matriz
3       Loja Matriz
4       Loja Matriz
           ...     
2995      Filial ES
2996      Filial ES
2997      Filial ES
2998      Filial ES
2999      Filial ES
Name: nome_loja, Length: 3000, dtype: object

In [21]:
df['Nome Funcionario'].unique

<bound method Series.unique of 0        José Maria
1        José Maria
2        José Maria
3        José Maria
4        José Maria
           ...     
2995    Victor Hugo
2996    Victor Hugo
2997    Victor Hugo
2998    Victor Hugo
2999    Victor Hugo
Name: Nome Funcionario, Length: 3000, dtype: object>

In [22]:
colunas = ['matricula_funcionario', 'nome_funcionario', 'cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega']

df.columns = colunas 

In [23]:
df.columns

Index(['matricula_funcionario', 'nome_funcionario', 'cargo', 'codigo_loja',
       'nome_loja', 'codigo_produto', 'descricao_produto', 'categoria',
       'preco_custo', 'valor_unitario', 'quantidade', 'comissao', 'dt_venda',
       'dt_entrega'],
      dtype='object')

In [26]:
df.nome_funcionario.unique()

array(['José Maria', 'Maria das Graças', 'Jorge Mateus', 'Marta Cury',
       'Ricardo Lemos', 'Reginaldo Sodré', 'Felipe Marinho',
       'Marcos Coelho', 'Rita Sampaio', 'Mário Henrique', 'Pamela Lima',
       'Victor Hugo'], dtype=object)

In [27]:
df.values

array([[123456111, 'José Maria', 'Vendedor', ..., nan,
        '28/09/2020 16:19', '05/10/2020 16:31'],
       [123456111, 'José Maria', 'Vendedor', ..., nan,
        '07/03/2020 12:47', '08/03/2020 12:47'],
       [123456111, 'José Maria', 'Vendedor', ..., nan,
        '21/04/2019 10:48', '23/04/2019 15:55'],
       ...,
       [123457113, 'Victor Hugo', 'Vendedor', ..., nan,
        '08/08/2020 14:46', '09/08/2020 14:07'],
       [123457113, 'Victor Hugo', 'Vendedor', ..., nan,
        '19/12/2019 09:21', '19/12/2019 10:51'],
       [123457113, 'Victor Hugo', 'Vendedor', ..., '0,09',
        '18/03/2019 15:40', '23/03/2019 17:52']], dtype=object)

In [28]:
df.to_numpy()

array([[123456111, 'José Maria', 'Vendedor', ..., nan,
        '28/09/2020 16:19', '05/10/2020 16:31'],
       [123456111, 'José Maria', 'Vendedor', ..., nan,
        '07/03/2020 12:47', '08/03/2020 12:47'],
       [123456111, 'José Maria', 'Vendedor', ..., nan,
        '21/04/2019 10:48', '23/04/2019 15:55'],
       ...,
       [123457113, 'Victor Hugo', 'Vendedor', ..., nan,
        '08/08/2020 14:46', '09/08/2020 14:07'],
       [123457113, 'Victor Hugo', 'Vendedor', ..., nan,
        '19/12/2019 09:21', '19/12/2019 10:51'],
       [123457113, 'Victor Hugo', 'Vendedor', ..., '0,09',
        '18/03/2019 15:40', '23/03/2019 17:52']], dtype=object)

In [29]:
df.shape

(3000, 14)

In [35]:
df.isnull().sum() / df.shape[0] *100

matricula_funcionario     0.0
nome_funcionario          0.0
cargo                     0.0
codigo_loja               0.0
nome_loja                 0.0
codigo_produto            0.0
descricao_produto         0.0
categoria                 0.0
preco_custo               0.0
valor_unitario            0.0
quantidade                0.0
comissao                 94.7
dt_venda                  0.0
dt_entrega                0.0
dtype: float64

In [36]:
df.comissao.unique()

array([nan, '0,05', '0,09', '0,07', '0,1'], dtype=object)

In [37]:
df.nunique()

matricula_funcionario      12
nome_funcionario           12
cargo                       1
codigo_loja                 4
nome_loja                   4
codigo_produto             20
descricao_produto          20
categoria                   4
preco_custo                20
valor_unitario             19
quantidade                  4
comissao                    4
dt_venda                 2994
dt_entrega               2989
dtype: int64

In [39]:
colunas = ['nome_funcionario', 'descricao_produto', 'categoria', 'valor_unitario']
df[colunas]

nome_funcionario    descricao_produto         categoria valor_unitario
0          José Maria                Fogão  Eletrodomésticos          404,1
1          José Maria              Colchão              Casa          249,9
2          José Maria            Geladeira  Eletrodomésticos         1346,9
3          José Maria           Smartphone       Eletrônicos         1676,9
4          José Maria  Máquina Lavar Roupa  Eletrodomésticos         1709,1
...               ...                  ...               ...            ...
2995      Victor Hugo      Aspirador de pó              Casa          189,9
2996      Victor Hugo       Liquidificador           Cozinha          142,4
2997      Victor Hugo            Batedeira           Cozinha           95,9
2998      Victor Hugo  Fritadeira elétrica           Cozinha            340
2999      Victor Hugo  Máquina Lavar Roupa  Eletrodomésticos         1709,1

[3000 rows x 4 columns]

In [40]:
df.set_index('matricula_funcionario')

nome_funcionario     cargo codigo_loja    nome_loja  \
matricula_funcionario                                                       
123456111                   José Maria  Vendedor       CL001  Loja Matriz   
123456111                   José Maria  Vendedor       CL001  Loja Matriz   
123456111                   José Maria  Vendedor       CL001  Loja Matriz   
123456111                   José Maria  Vendedor       CL001  Loja Matriz   
123456111                   José Maria  Vendedor       CL001  Loja Matriz   
...                                ...       ...         ...          ...   
123457113                  Victor Hugo  Vendedor       CL004    Filial ES   
123457113                  Victor Hugo  Vendedor       CL004    Filial ES   
123457113                  Victor Hugo  Vendedor       CL004    Filial ES   
123457113                  Victor Hugo  Vendedor       CL004    Filial ES   
123457113                  Victor Hugo  Vendedor       CL004    Filial ES   

                       codigo_produto    descricao_produto         categoria  \
matricula_funcionario                                                          
123456111                       10013                Fogão  Eletrodomésticos   
123456111                       10018              Colchão              Casa   
123456111                       10014            Geladeira  Eletrodomésticos   
123456111                       10001           Smartphone       Eletrônicos   
123456111                       10004  Máquina Lavar Roupa  Eletrodomésticos   
...                               ...                  ...               ...   
123457113                       10006      Aspirador de pó              Casa   
123457113                       10011       Liquidificador           Cozinha   
123457113                       10007            Batedeira           Cozinha   
123457113                       10010  Fritadeira elétrica           Cozinha   
123457113                       10004  Máquina Lavar Roupa  Eletrodomésticos   

                      preco_custo valor_unitario  quantidade comissao  \
matricula_funcionario                                                   
123456111                   210,9          404,1           1      NaN   
123456111                   109,9          249,9           1      NaN   
123456111                   699,9         1346,9           1      NaN   
123456111                   899,9         1676,9           1      NaN   
123456111                    1099         1709,1           1     0,05   
...                           ...            ...         ...      ...   
123457113                    88,9          189,9           3      NaN   
123457113                    59,9          142,4           3      NaN   
123457113                    49,9           95,9           3      NaN   
123457113                   187,9            340           3      NaN   
123457113                    1099         1709,1           3     0,09   

                               dt_venda        dt_entrega  
matricula_funcionario                                      
123456111              28/09/2020 16:19  05/10/2020 16:31  
123456111              07/03/2020 12:47  08/03/2020 12:47  
123456111              21/04/2019 10:48  23/04/2019 15:55  
123456111              07/05/2020 17:59  08/05/2020 14:31  
123456111              14/08/2019 16:56  19/08/2019 15:52  
...                                 ...               ...  
123457113              04/11/2019 15:40  05/11/2019 10:40  
123457113              24/06/2019 09:04  24/06/2019 10:50  
123457113              08/08/2020 14:46  09/08/2020 14:07  
123457113              19/12/2019 09:21  19/12/2019 10:51  
123457113              18/03/2019 15:40  23/03/2019 17:52  

[3000 rows x 13 columns]

In [42]:
df.describe()


matricula_funcionario  codigo_produto   quantidade
count           3.000000e+03     3000.000000  3000.000000
mean            1.234567e+08    10010.468667     2.453333
std             3.489977e+02        5.772590     1.107955
min             1.234561e+08    10001.000000     1.000000
25%             1.234563e+08    10006.000000     1.000000
50%             1.234567e+08    10011.000000     2.000000
75%             1.234570e+08    10015.000000     3.000000
max             1.234571e+08    10020.000000     4.000000

In [44]:
df.value_counts()

matricula_funcionario  nome_funcionario  cargo     codigo_loja  nome_loja    codigo_produto  descricao_produto    categoria         preco_custo  valor_unitario  quantidade  comissao  dt_venda          dt_entrega      
123456111              José Maria        Vendedor  CL001        Loja Matriz  10004           Máquina Lavar Roupa  Eletrodomésticos  1099         1709,1          1           0,05      05/09/2019 10:36  10/09/2019 12:46    1
123456888              Rita Sampaio      Vendedor  CL003        Filial SP    10004           Máquina Lavar Roupa  Eletrodomésticos  1099         1709,1          3           0,09      26/09/2019 10:40  30/09/2019 11:26    1
                                                                                                                                                                 2           0,07      12/01/2020 12:31  15/01/2020 11:36    1
                                                                                                                 

In [45]:
df.nunique()

matricula_funcionario      12
nome_funcionario           12
cargo                       1
codigo_loja                 4
nome_loja                   4
codigo_produto             20
descricao_produto          20
categoria                   4
preco_custo                20
valor_unitario             19
quantidade                  4
comissao                    4
dt_venda                 2994
dt_entrega               2989
dtype: int64

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   matricula_funcionario  3000 non-null   int64 
 1   nome_funcionario       3000 non-null   object
 2   cargo                  3000 non-null   object
 3   codigo_loja            3000 non-null   object
 4   nome_loja              3000 non-null   object
 5   codigo_produto         3000 non-null   int64 
 6   descricao_produto      3000 non-null   object
 7   categoria              3000 non-null   object
 8   preco_custo            3000 non-null   object
 9   valor_unitario         3000 non-null   object
 10  quantidade             3000 non-null   int64 
 11  comissao               159 non-null    object
 12  dt_venda               3000 non-null   object
 13  dt_entrega             3000 non-null   object
dtypes: int64(3), object(11)
memory usage: 328.3+ KB
